// src/components/content/characters.tsx
import JapaneseHeading from '@components/japaneseHeading'
import Box from '@components/primitives/box'
import Heading from '@components/primitives/heading'

// types
import type { NextComponentType, NextPageContext } from 'next'
import type { ICharacter } from '@utils/ts/aniListApiTypes'

interface Props {
  data: ICharacter[]
}

const Characters: NextComponentType<NextPageContext, {}, Props> = (
  props: Props
) => {
  return (
    <Box>
      <Heading as="h1" css={{ pb: '$4' }}>
        stinky main characters
        <JapaneseHeading css={{ left: 0, top: '-25%' }}>
          ボボ の 電波な奴
        </JapaneseHeading>
      </Heading>
      <Box
        css={{
          display: 'flex',
          flexWrap: 'wrap',
          flexDirection: 'row',
          justifyContent: 'center',
          gridGap: '$4'
        }}
      >
        {props.data.map((char: ICharacter, index: number) => (
          <Box
            css={{
              display: 'flex',
              flexDirection: 'column',
              justifyContent: 'center',
              alignItems: 'center'
            }}
            key={index}
          >
            <img
              width={100}
              height={100}
              alt={char.node.name.first}
              src={char.node.image.large}
            />
            <Heading as="h5" css={{ py: '$2' }}>
              {char.node.name?.first} <br /> {char.node.name?.last}
            </Heading>
          </Box>
        ))}
      </Box>
    </Box>
  )
}

export default Characters

// src/components/content/characters.vue
<script lang="ts" setup>
import JapaneseHeading from "@components/jpHeading.vue";
import type { ICharacter } from "@utils/ts/aniListApiTypes";

const { data } = defineProps<{
  data: ICharacter[];
}>();
</script>

<template>
  <h1 class="pb-4">
    stinky main characters
    <JapaneseHeading left="0" top="-25%">ボボ の 電波な奴</JapaneseHeading>
  </h1>
  <div class="flex flex-row flex-wrap justify-center gap-4">
    <div v-for="char in data" class="flex flex-col items-center justify-center">
      <img
        class="h-28 w-28"
        :alt="char.node.name.first || undefined"
        :src="char.node.image.large"
      />
      <h5 class="pt-2">
        {{ char.node.name?.first }} <br />
        {{ char.node.name?.last }}
      </h5>
    </div>
  </div>
</template>
